openapi: 3.0.3
info:
  title: WIC MT Demo Project Mock API
  description: A Mock API wrapper around the SPIRIT MIS for the Special Supplemental Nutrition Program for Women, Infants, and Children (WIC)
  version: "2022-06-21"
  contact:
    name: Nava WIC MT Demo Project Team
    url: https://www.navapbc.com/
    email: mt-wic-demo-project@navapbc.com

security:
  - api_key: []
  

servers:
  - url: /v1
    description: Development server

tags:
  - name: Eligibility
  - name: Health
    description: API Health and Integrity

paths:
  /healthcheck:
    get:
      security:
        - {} # No authentication required
      tags:
        - Health
      summary: Healthcheck for the API
      operationId: api.route.healthcheck.healthcheck_get
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: boolean


  /eligibility-screener:
    post:
      security:
        - api_key: []
      tags:
        - Eligibility
      summary: Submit an eligibility screener
      operationId: api.route.eligibility.eligibility_screener_post
      responses:
        "201":
          description: Eligibility screener was successfully submitted
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/SuccessfulResponse'
                  - properties:
                      data:
                        $ref: "#/components/schemas/EligibilityScreenerResponse"
        "400":
          description: An unsuccessful request returns a 400 status code if one or more errors occurred.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EligibilityScreenerRequest"


components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-Auth
      in: header
      x-apikeyInfoFunc: api.auth.api_key_auth.api_key_auth
  schemas:
    EligibilityScreenerBase:
      type: object
      properties:
        first_name:
          type: string
          example: Jane
          description: The applicants first name
        last_name:
          type: string
          example: Doe
          description: The applicants last name
        phone_number:
          type: string
          example: "224-705-2345"
          pattern: '^([0-9]|\*){3}\-([0-9]|\*){3}\-[0-9]{4}$'
        eligibility_categories:
          type: array
          items:
            type: string
            enum:
              - "pregnant"
              - "baby"
              - "guardian"
              - "loss"
          example: ["pregnant"]
          description: The list of categories that make the applicant eligible
        has_prior_wic_enrollment:
          type: boolean
          example: false
          description: Whether or not the applicant or anyone in their household has prior WIC enrollment
        eligibility_programs:
          type: array
          items:
            type: string
            enum:
              - "insurance"
              - "snap"
              - "tanf"
          example: ["insurance", "snap"]
          description: Other programs the applicant is already enrolled in
        household_size:
          type: integer
          nullable: true
          example: 1
          description: Household size - only necessary if no other current eligibility programs
        zip_code:
          type: string
          pattern: '^[0-9]{5}((?:-[0-9]{4})?|(?:-\*{4})?)$'
          example: "12345"
          description: The ZIP code of the applicant
        wic_clinic:
          type: string
          example: "BEAVERHEAD CPH WIC\n41 Barrett Street Dillon, MT 59725"
          description: The full address of the chosen WIC clinic
        applicant_notes:
          type: string
          nullable: true
          example: "Example notes"
          description: Any additional applicant notes

    EligibilityScreenerRequest:
      allOf:
        - $ref: "#/components/schemas/EligibilityScreenerBase"

    EligibilityScreenerResponse:
      type: object
      properties:
        eligibility_screener_id:
          type: string
          format: uuid
          example: "2f0f58a0-fcad-465b-b474-ee6c961cd6e3"
      allOf:
        - $ref: "#/components/schemas/EligibilityScreenerBase"

    SuccessfulResponse:
      type: object
      properties:
        status_code:
          type: integer
          example: 201
        message:
          type: string
          example: "success"
        data:
          oneOf:
            - type: array
            - type: object
        warnings:
          type: array
          items:
            $ref: "#/components/schemas/ValidationErrorDetail"
      required: ["status_code"]
      additionalProperties: false

    ErrorResponse:
      type: object
      properties:
        status_code:
          type: integer
          example: 400
        message:
          type: string
          example: "Unable to add record"
        data:
          oneOf:
            - type: array
            - type: object
        warnings:
          type: array
          items:
            $ref: "#/components/schemas/ValidationErrorDetail"
        errors:
          type: array
          items:
            $ref: "#/components/schemas/ValidationErrorDetail"
      required: ["status_code", "errors"]
      additionalProperties: false

    ValidationErrorDetail:
      type: object
      properties:
        type:
          example: "required"
          type: string
        message:
          example: "request.first_name is required."
          description: "Somewhat user-friendly description of the error. May contain PII."
          type: string
        rule:
          description: >
            Usage varies depending on the source of the validation error. OpenAPI validation
            errors will set this to the expected value behavior (i.e the max length, or pattern).
          oneOf:
            - type: string
            - type: number
            - type: integer
            - type: boolean
            - type: array
            - type: object
          nullable: true
        field:
          description: "Field path, when the error is associated with a specific field."
          example: "request.first_name"
          nullable: true
          type: string
      additionalProperties: false




