openapi: 3.0.3
info:
  title: WIC MT Demo Project Mock API
  description: A Mock API wrapper around the SPIRIT MIS for the Special Supplemental Nutrition Program for Women, Infants, and Children (WIC)
  version: "2022-06-21"

servers:
  - url: /v1
    description: Development server

paths:
  /healthcheck:
    get:
      summary: Healthcheck for the API
      operationId: api.api.healthcheck_get
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: boolean


  /eligibility-screener:
    post:
      summary: Submit an eligibility screener
      operationId: api.eligibility.eligibility_screener_post
      responses:
        "201":
          description: Eligibility screener was successfully submitted
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/SuccessfulResponse'
                  - properties:
                      data:
                        $ref: "#/components/schemas/EligibilityScreenerResponse"
        "400":
          description: TODO - figure out error codes we actually will use
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EligibilityScreenerRequest"


components:
  schemas:
    EligibilityScreenerRequest:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        phone_number:
          type: string
          example: "224-705-2345"
          pattern: '^([0-9]|\*){3}\-([0-9]|\*){3}\-[0-9]{4}$'
          nullable: true
        
      required: ["first_name", "last_name"]

    SuccessfulResponse:
      type: object
      properties:
        status_code:
          type: integer
        message:
          type: string
        data:
          oneOf:
            - type: array
            - type: object
        warnings:
          type: array
          items:
            $ref: "#/components/schemas/ValidationErrorDetail"
      required: ["status_code"]
      additionalProperties: false

    ErrorResponse:
      type: object
      properties:
        status_code:
          type: integer
        message:
          type: string
        data:
          oneOf:
            - type: array
            - type: object
        warnings:
          type: array
          items:
            $ref: "#/components/schemas/ValidationErrorDetail"
        errors:
          type: array
          items:
            $ref: "#/components/schemas/ValidationErrorDetail"
      required: ["status_code", "errors"]
      additionalProperties: false

    ValidationErrorDetail:
      type: object
      properties:
        type:
          example: "required"
          type: string
        message:
          example: "request.first_name is required."
          description: "Somewhat user-friendly description of the error. May contain PII."
          type: string
        rule:
          description: >
            Usage varies depending on the source of the validation error. OpenAPI validation
            errors will set this to the expected value behavior (i.e the max length, or pattern).
          oneOf:
            - type: string
            - type: number
            - type: integer
            - type: boolean
            - type: array
            - type: object
          nullable: true
        field:
          description: "Field path, when the error is associated with a specific field."
          example: "request.first_name"
          nullable: true
          type: string
      additionalProperties: false

    EligibilityScreenerResponse:
      type: object
      properties:
        eligibility_screener_id:
          type: string
          format: uuid
          example: "2f0f58a0-fcad-465b-b474-ee6c961cd6e3"


