"""WMDP-196 add wic clinic

Revision ID: 5fff206b7322
Revises: 5b996cf0144e
Create Date: 2022-09-07 15:34:02.101507

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5fff206b7322"
down_revision = "5b996cf0144e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("eligibility_screener", sa.Column("wic_clinic", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("eligibility_screener", "wic_clinic")
    # ### end Alembic commands ###
