"""test migration2

Revision ID: 0004c84fe35a
Revises: 5fff206b7322
Create Date: 2022-09-16 12:16:40.037515

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0004c84fe35a"
down_revision = "5fff206b7322"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
