"""WMDP-193 add submitted timestamp

Revision ID: 5b996cf0144e
Revises: 7b9a08694907
Create Date: 2022-09-06 13:56:30.843021

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5b996cf0144e"
down_revision = "7b9a08694907"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "eligibility_screener",
        sa.Column("added_to_eligibility_screener_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("eligibility_screener", "added_to_eligibility_screener_at")
    # ### end Alembic commands ###
