"""WMDP-126 - add screener model

Revision ID: 7b9a08694907
Revises: b78c1c9029f5
Create Date: 2022-09-02 12:43:41.745235

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7b9a08694907"
down_revision = "b78c1c9029f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "eligibility_screener",
        sa.Column("eligibility_categories", postgresql.ARRAY(sa.Text()), nullable=True),
    )
    op.add_column(
        "eligibility_screener", sa.Column("has_prior_wic_enrollment", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "eligibility_screener",
        sa.Column("eligibility_programs", postgresql.ARRAY(sa.Text()), nullable=True),
    )
    op.add_column("eligibility_screener", sa.Column("household_size", sa.Integer(), nullable=True))
    op.add_column("eligibility_screener", sa.Column("zip_code", sa.Text(), nullable=False))
    op.add_column("eligibility_screener", sa.Column("applicant_notes", sa.Text(), nullable=True))
    op.alter_column("eligibility_screener", "first_name", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("eligibility_screener", "last_name", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("eligibility_screener", "phone_number", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("eligibility_screener", "phone_number", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("eligibility_screener", "last_name", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("eligibility_screener", "first_name", existing_type=sa.TEXT(), nullable=True)
    op.drop_column("eligibility_screener", "applicant_notes")
    op.drop_column("eligibility_screener", "zip_code")
    op.drop_column("eligibility_screener", "household_size")
    op.drop_column("eligibility_screener", "eligibility_programs")
    op.drop_column("eligibility_screener", "has_prior_wic_enrollment")
    op.drop_column("eligibility_screener", "eligibility_categories")
    # ### end Alembic commands ###
