"""first migration

Revision ID: b78c1c9029f5
Revises:
Create Date: 2022-08-29 14:29:10.441061

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b78c1c9029f5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "eligibility_screener",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("eligibility_screener_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("first_name", sa.Text(), nullable=True),
        sa.Column("last_name", sa.Text(), nullable=True),
        sa.Column("phone_number", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("eligibility_screener_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    op.execute("GRANT ALL ON SCHEMA public TO PUBLIC")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("eligibility_screener")
    # ### end Alembic commands ###
