"""Add wic_agency.

Revision ID: 8ed905638aa5
Revises: 5fff206b7322
Create Date: 2022-10-27 05:59:35.248008

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8ed905638aa5"
down_revision = "5fff206b7322"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("eligibility_screener", sa.Column("wic_agency", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("eligibility_screener", "wic_agency")
    # ### end Alembic commands ###
