"""test migration

Revision ID: eba97ae6ec0e
Revises: 5fff206b7322
Create Date: 2022-09-16 16:16:20.549497

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "eba97ae6ec0e"
down_revision = "5fff206b7322"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
