name: Mock API Checks

on:
  push:
    branches:
      - main
    paths:
      - app/**
      - .github/workflows/api-checks.yml
  pull_request:
    paths:
      - app/**
      - .github/workflows/api-checks.yml

defaults:
  run:
    working-directory: ./app

env:
  # Some commands in the Makefile check if this is set
  # and add additional parameters to the commands called
  CI: true

# this workflow should be updated/merged when WMDP-123. etc are merged
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build container
        run: make build

      - name: Run format check
        run: make format-check

      - name: Run linting
        run: make lint
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Security Check
        run: |
          echo "Placeholder until security tools are installed"
          exit 0
  test:
    needs: [lint, security]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start tests
        run: make test-coverage