# Deploy steps:
# - Build and tag a docker release image
# - Upload the docker image to ECR
# - Trigger a rotation of the ECS service containers
#
# The underlying terraform is managed in the wic-mt-demo-project repo and references the uploaded docker image.

name: Mock API Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default_value: "test"
        description: |
          Choose an environment to deploy changes to.
        type: choice
        options:
          - test
          - stage
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy Mock API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Tag commit
        # Running `git push --tags` may not be necessary, but we should test this. We want to be able to view tags that github creates by going to https://github.com/navapbc/wic-mt-demo-project-eligibility-screener/tags
        # Not sure if we are able to do a `git push --tags` from inside the container job thing
        run: |
          git tag -a ${{github.event.inputs.environment || 'test' }} -m TODO dummy message
          git push --tags