# Deploy steps:
# - Build and tag a docker release image
# - Upload the docker image to ECR
# - Trigger a rotation of the ECS service containers
#
# The underlying terraform is managed in the wic-mt-demo-project repo and references the uploaded docker image.

name: Mock API Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default_value: "test"
        description: |
          Choose an environment to deploy changes to.
        type: choice
        options:
          - test
          - stage
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy Mock API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{github.event.inputs.environment || 'test' }}
          message: "Tag created in ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          force_push_tag: true